### ISSUE TITLE
3freq error

### ISSUE THREAD

**Issue by jorgehatccrma** [MusicDynamicsLab/GrFNNToolbox#11]
I tried running a model using '3freq' connection type in `connectAdd` when self connecting a GrFNN, but I got the following error:

```matlab
Error using .*
Matrix dimensions must agree.

Error in connectAdd (line 232)
con.kappa = con.kappa .* mask;
```

I've tried using different GrFNN sizes, but the result is always the same. This error doesn't happen when connecting different GrFNNs using '3freq'. Should I assume is not possible to use '3freq' on a GrFNN connected to itself? 

If it is abug then the problem is probably in `inputShapeInternal.m` or `inputExponentsInternal.m`

**Comment by jichulkim** [comment]
This issue has been fixed.
