### ISSUE TITLE
3freq error 2

### ISSUE THREAD

**Issue by jorgehatccrma** [MusicDynamicsLab/GrFNNToolbox#12]
This is different from (but probably related to) #11 

When running a model with '3freq' connections between different GrFNNs I get the following error:

```matlab
Error using .*
Matrix dimensions must agree.

Error in zdot (line 69)
        x_int = con{cx}.C.*(e.^((N1+N2+D2-2)/2)) ...

Error in odeRK4fs (line 65)
            M.n{nx}.k{kx} = h*zfun(M, s, ind, nx);

Error in main (line 17)
M = odeRK4fs(M,s);
```

I check the dimension and `con{cx}.C` is different from the rest of the matrices involved (`N1`, `N2`, `D2`, `Z1`, `Z2` and `Z`). As a test I connected 2 GrFNNs with 21 oscillators each. The sizes right before line 69 in `zdot.m` are:

```
con{cx}.C: 21 x 21
N1: 21 x 210
N2: 21 x 210
D2: 21 x 210
Z1: 21 x 210
Z2: 21 x 210
Z: 21 x 210
```

**Comment by jichulkim** [comment]
This issue has been fixed.
