### ISSUE TITLE
Plotting from within functions?

### ISSUE THREAD

**Issue by jorgehatccrma** [MusicDynamicsLab/GrFNNToolbox#3]
This is a comment more than an actual issue. Feel free to discard if you don't agree with my opinions!

I like the ability of updating a plot as the network integrates. That said, something feels wrong about mixing display code with computation/integration code. In my mind, odeRK4.m should be concerned only with integration and shouldn't even be aware of the possibility of displaying. After years of coding, I strongly believe that encapsulation and single responsibility are good things! 

I understand that:

  1. The original idea was that it would make sense to display from within the integrator if the integrator if it is running on GPU (after all the data is already there, so why bringing it back to CPU and the resend it to GPU, right?)
  2. Matlab is not a great programing language, so generally accepted principles of software design are not always easy to be implemented

Those are valid points. Regarding the first one, after talking with Ed, it seems like this was a nice though, but in practice this is not as straight-forward as it seems, so maybe we have to deal with that some other way. To the second point, currently the paradigm is functions + global vars. I don't see how we could separate the display and integration code under this paradigm. Maybe we could discuss on how to use a OOP architecture? This is a BIG change, I know, so it is probably not going to happen in this version. Could it be for Toolbox 2.0? Disclaimer: I've done some OOP with matlab in the past, but I'm far from being an expert. I do know enough to know that it can help a lot, but is far from being a full-fleshed OOP language, so it might not be possible to implement what I'm talking about at all (at least not easily).

Again, this is just a brain dump, not an actual issue, so feel free to close and delete!

**Comment by jichulkim** [comment]
Thank you for your suggestions. Starting with version 1.2, all live displays are handled by functions outside the integrator. These are `stimulusLiveDisplay.m`, `networkLiveDisplay.m`, and `connectionLiveDisplays`, each of them called from `odeRK4fs.m`.
